# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ '8', '11', '17' ]
    name: Build/Test with Java ${{ matrix.Java }}

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        java-version: ${{ matrix.java }}
        distribution: 'temurin'
        cache: maven

    - name: Build with Maven
      run: mvn clean install -Prun-its

    - name: Test coverage
      # Only publish code coverage results for one JDK version
      if: ${{ matrix.java == '8' }}
      run: mvn jacoco:report coveralls:report
      env:
        COVERALLS_API_KEY: ${{ secrets.COVERALLS_API_KEY }}

